Repository Simplon-hdf/API-bots-discord-documentation, pull requests merged in 2024-11, with the labels that each got.

#134 docs(bot-onboarding): check email recap spelling
  doc/bot-onboarding/echanges-client/echanges-30-10-24/mail-recap.md
Labels: documentation, bot onboarding

#135 docs(bot-onboarding): add dictionnaire-de-donnees file
  doc/bot-onboarding/bdd/dictionnaire-de-donnees.md
Labels: documentation, bot onboarding

#138 docs(bot-onboarding): review management rules and add questions
  doc/bot-onboarding/echanges-client/stock-questions.md
  doc/bot-onboarding/regles-gestion.md
Labels: documentation, bot onboarding

#137 docs(bot-feedback): update regles-gestion.md
  doc/bot-feedback/regles-gestion.md
Labels: documentation, bot feedback

#139 docs(bot-feedback): add new file 'dictionnaire-donnees' in bdd directory
  doc/bot-feedback/bdd/dictionnaire-donnees.md
Labels: documentation, bot feedback

#140 docs(bot-signature): add security plan file
  doc/bot-signature/securite.md
Labels: documentation, bot signature

#142 docs(CODEOWNERS): add code owners file
  CODEOWNERS
Labels: documentation

#141 docs(bot-signature): add rgpd section
  doc/bot-signature/securite.md
Labels: documentation, bot signature

#143 docs(bot-signature): update business rules
  doc/bot-signature/regles-gestion.md
Labels: documentation, bot signature

#144 docs(bot-onboarding): review management rules
  doc/bot-onboarding/regles-gestion.md
Labels: documentation, bot onboarding

#146 docs(CODEOWNERS): add bot-community members
  CODEOWNERS
Labels: documentation, enhancement

#148 docs(bot-feedback): add new directory and new file
  doc/bot-feedback/securite/RPGD.md
Labels: documentation, bot feedback

#147 docs: add the file "securite-globale.md"
  doc/bot-onboarding/securite/rgpd.md
  doc/securite-globale.md
Labels: documentation, bot onboarding

#149 docs: add security strategy
  doc/securite-globale.md
Labels: documentation

#150 docs(doc): resume global security
  doc/securite-globale.md
Labels: documentation

#152 docs(doc): create security folder
  doc/securite/API.md
  doc/securite/README.md
Labels: documentation

#154 docs(securite): add back-end.md
  doc/securite/back-end.md
Labels: documentation, security

#156 docs(securite): add summary in README.md for the directory
  doc/securite/README.md
Labels: documentation, security

#157 docs(securite): add frontend.md
  doc/bot-community/contexte-et-enjeux.md
  doc/enjeux.md
  doc/securite/frontend.md
Labels: documentation, security

#158 docs(securite): move 'introduction' to the correct folder
  doc/securite/introduction.md
Labels: documentation, security

#159 docs(securite): add new part 'Utilisation des UUID' in back-end.md file
  doc/securite-globale.md
  doc/securite/back-end.md
Labels: documentation, security

#160 docs(securite): update summary and add links
  doc/securite/01-introduction.md
  doc/securite/02-back-end.md
  doc/securite/03-front-end.md
  doc/securite/README.md
Labels: documentation, security

#164 docs(securite): add API.md part
  doc/securite/02-back-end.md
  doc/securite/API.md
Labels: documentation, security

#165 docs(securite): add 'Politique de sauvegarde' block
  doc/securite/02-back-end.md
Labels: documentation, security

#166 docs(securite): update links for some part
  doc/securite/README.md
Labels: documentation, security

#167 docs(bot-onboarding): add the dictionary data
  doc/bot-onboarding/bdd/dictionnaire-de-donnees.md
Labels: documentation, bot onboarding

#168 docs(bot-feedback): add data dictionary
  doc/bot-feedback/bdd/dictionnaire-donnees.md
Labels: documentation, bot feedback
